Fix cmake install of samples
Samples should now be packaged. However, now the samples need to be run as GROUP/SAMPLE/SAMPLE_BIN

diff --git a/snap/local/bin/launcher b/snap/local/bin/launcher
--- a/snap/local/bin/launcher
+++ b/snap/local/bin/launcher
@@ -1,105 +1,105 @@
 #!/usr/bin/env bash
 
-function usage () {
-	echo "usage: cuda-samples [-hla] sample [args ...]"
-	echo
-	echo "positional arguments:"
-	echo "sample  cuda sample to execute"
-	echo "args    optional arguments to pass to the sample"
-	echo
-	echo "options:"
-	echo "-h      show this help message and exit"
-	echo "-l      list the samples available"
-	echo "-a      execute all samples"
+function usage() {
+    echo "usage: cuda-samples [-hla] sample [args ...]"
+    echo
+    echo "positional arguments:"
+    echo "sample  cuda sample to execute"
+    echo "args    optional arguments to pass to the sample"
+    echo
+    echo "options:"
+    echo "-h      show this help message and exit"
+    echo "-l      list the samples available"
+    echo "-a      execute all samples"
 }
 
-SAMPLES_DIR="$SNAP/usr/local/cuda/samples/bin"
+SAMPLES_DIR="$SNAP/usr/local/cuda/samples"
 
-function list_samples () {
-	if [[ ! -d "$SAMPLES_DIR" ]] ; then
-		echo "list_samples: samples dir $SAMPLES_DIR not found"
-		return 1
-	fi
-	echo "$(find "$SAMPLES_DIR" -maxdepth 1 -type f -executable -printf "%f\n")"
+function list_samples() {
+    if [[ ! -d "$SAMPLES_DIR" ]]; then
+        echo "list_samples: samples dir $SAMPLES_DIR not found"
+        return 1
+    fi
+    echo "$(find "$SAMPLES_DIR" -type f -executable -printf "%P\n")"
 }
 
-function exec_sample () {
-	if [[ -z "$1" ]] ; then
-		echo "exec_sample: missing required argument -- sample"
-		return 1
-	fi
+function exec_sample() {
+    if [[ -z "$1" ]]; then
+        echo "exec_sample: missing required argument -- sample"
+        return 1
+    fi
 
-	sample="$1"
-	args="${@:2}"
+    sample="$1"
+    args="${@:2}"
 
-	if [[ ! -f "$SAMPLES_DIR/$sample" ]] ; then
-		echo "exec_sample: sample $sample not found in $SAMPLES_DIR"
-		return 1
-	fi
+    if [[ ! -f "$SAMPLES_DIR/$sample" ]]; then
+        echo "exec_sample: sample $sample not found in $SAMPLES_DIR"
+        return 1
+    fi
 
-	pushd "$SAMPLES_DIR" > /dev/null || return 1
-	"$SAMPLES_DIR/$sample" "$args"
-	ret=$?
-	popd > /dev/null || return 1
-	return $ret
+    pushd "$SAMPLES_DIR" >/dev/null || return 1
+    "$SAMPLES_DIR/$sample" "$args"
+    ret=$?
+    popd >/dev/null || return 1
+    return $ret
 }
 
-function exec_all () {
-	samples="$(list_samples)"
-	ret=$?
-	if [[ $ret -ne 0 ]] ; then
-		echo "exec_all: error when calling list-samples -- $samples"
-		return $ret
-	fi
+function exec_all() {
+    samples="$(list_samples)"
+    ret=$?
+    if [[ $ret -ne 0 ]]; then
+        echo "exec_all: error when calling list-samples -- $samples"
+        return $ret
+    fi
 
-	while read -r sample ; do
-		name=$(basename -- "$sample")
-		case "$name" in
-			dwtHaar1D|jpegNPP)
-				echo "==== SKIPPING $name ===="
-				echo "needs specific arguments"
-				echo
-				;;
-			*)
-				echo "==== RUNNING $name ===="
-				exec_sample "$name"
-				ret=$?
-				if [[ $ret -ne 0 ]] ; then
-					return $ret
-				fi
-				echo
-				;;
-		esac
-	done <<< "$samples"
-	return $ret
+    while read -r sample; do
+        name=$(basename -- "$sample")
+        case "$name" in
+        dwtHaar1D | jpegNPP)
+            echo "==== SKIPPING $name ===="
+            echo "needs specific arguments"
+            echo
+            ;;
+        *)
+            echo "==== RUNNING $name ===="
+            exec_sample "$name"
+            ret=$?
+            if [[ $ret -ne 0 ]]; then
+                return $ret
+            fi
+            echo
+            ;;
+        esac
+    done <<<"$samples"
+    return $ret
 }
 
-while getopts "hla" opt ; do
-	case ${opt} in
-		h)
-			usage
-			exit
-			;;
-		l)
-			list_samples
-			exit $?
-			;;
-		a)
-			exec_all
-			exit $?
-			;;
-		*)
-			usage
-			exit 1
-			;;
-	esac
+while getopts "hla" opt; do
+    case ${opt} in
+    h)
+        usage
+        exit
+        ;;
+    l)
+        list_samples
+        exit $?
+        ;;
+    a)
+        exec_all
+        exit $?
+        ;;
+    *)
+        usage
+        exit 1
+        ;;
+    esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
-if [[ -z "$1" ]] ; then
-	echo "$0: missing position argument -- sample"
-	usage
-	exit 1
+if [[ -z "$1" ]]; then
+    echo "$0: missing position argument -- sample"
+    usage
+    exit 1
 fi
 
 exec_sample "$1" "${@:2}"
